db:
  host: localhost
  port: 5432
  user: postgres
  password: r00tsql
  db: construction_system

server:
<<<<<<< Updated upstream
  port: 8080
=======
  port: 8080
  allowOrigin: https://con-dev.ratko.co

>>>>>>> Stashed changes
