version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_docker
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: r00tsql
    volumes:
      - database_dockerizing:/var/lib/postgresql/data
      - ./dbshell:/docker-entrypoint-initdb.d/
    networks:
      - fullstack
  api:
    container_name: construction_system
    build: .
    ports:
      - 8080:8080
    restart: always
    volumes:
      - api_volume:/usr/src/app/
    depends_on:
      - postgres
    networks:
      - fullstack

volumes:
  database_dockerizing:
  api_volume:

networks:
  fullstack:
    driver: bridge